/**
 * exportUtils.js
 * Utility functions for exporting solutions, problem sheets, and candidate portfolios
 * into clean GitHub-flavored Markdown (.md) or triggering printer-friendly views.
 */

// Helper to download a string as a file in the browser
export function downloadFile(filename, content, mimeType = "text/markdown;charset=utf-8;") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * 1. Export Solution Deconstruction to Markdown
 */
export function exportSolutionMarkdown(solution) {
  if (!solution) return;

  const title = solution.title || "AlgoCraft_Solution";
  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_breakdown.md`;

  const md = `# ${title}
**Difficulty:** ${solution.difficulty || "Medium"} | **Category:** ${solution.category || "Algorithms"} | **Platform:** AlgoCraft Free Studio

---

## 📌 Problem Statement
${solution.problemStatement || "No problem statement provided."}

${
  solution.examples && solution.examples.length > 0
    ? `### Examples
${solution.examples
  .map(
    (ex, i) => `**Example ${i + 1}:**
- **Input:** \`${ex.input}\`
- **Output:** \`${ex.output}\`
${ex.explanation ? `- **Explanation:** ${ex.explanation}\n` : ""}`
  )
  .join("\n")}`
    : ""
}

---

## 💡 Core Intuition & Mental Model
${solution.intuition || "See solution approaches below."}

---

## 🚀 Solutions Evolution

### 1. Brute Force Approach
- **Time Complexity:** \`${solution.bruteForce?.timeComplexity || "O(n^2)"}\`
- **Space Complexity:** \`${solution.bruteForce?.spaceComplexity || "O(1)"}\`
- **Explanation:** ${solution.bruteForce?.explanation || "Exhaustive search approach."}

\`\`\`javascript
${solution.bruteForce?.code || "// Code not available"}
\`\`\`

---

### 2. Better / Intermediate Approach
- **Time Complexity:** \`${solution.better?.timeComplexity || "O(n log n)"}\`
- **Space Complexity:** \`${solution.better?.spaceComplexity || "O(n)"}\`
- **Explanation:** ${solution.better?.explanation || "Intermediate optimization approach."}

\`\`\`javascript
${solution.better?.code || "// Code not available"}
\`\`\`

---

### 3. Optimal / FAANG Interview Ready Approach
- **Time Complexity:** \`${solution.optimal?.timeComplexity || "O(n)"}\`
- **Space Complexity:** \`${solution.optimal?.spaceComplexity || "O(1)"}\`
- **Explanation:** ${solution.optimal?.explanation || "Optimal linear or sub-linear approach."}

\`\`\`javascript
${solution.optimal?.code || "// Code not available"}
\`\`\`

---

## ⚠️ Pitfalls & Edge Cases to Avoid
${
  solution.pitfalls && solution.pitfalls.length > 0
    ? solution.pitfalls.map((p) => `- ⚠️ ${p}`).join("\n")
    : "- Handle empty inputs, single element boundaries, duplicates, and integer overflow."
}

---
*Generated by AlgoCraft — 100% Free AI DSA Mentor & Interview Studio*
`;

  downloadFile(safeFilename, md);
}

/**
 * 2. Export Problem Sheet with Section-wise Checkboxes
 */
export function exportSheetMarkdown(sheet) {
  if (!sheet) return;

  const title = sheet.title || "DSA_Problem_Sheet";
  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]/g, "_")}.md`;

  const total = sheet.sections?.reduce((sum, s) => sum + (s.problems?.length || 0), 0) || 0;
  const completed = sheet.sections?.reduce(
    (sum, s) => sum + (s.problems?.filter((p) => p.completed)?.length || 0),
    0
  ) || 0;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  let md = `# 📋 ${title}
> ${sheet.description || "Curated DSA Problem Sheet on AlgoCraft"}
> **Progress:** ${completed}/${total} Solved (${pct}%)

---

`;

  if (sheet.sections && sheet.sections.length > 0) {
    sheet.sections.forEach((sec, idx) => {
      const secTotal = sec.problems?.length || 0;
      const secDone = sec.problems?.filter((p) => p.completed)?.length || 0;
      md += `### ${idx + 1}. ${sec.title} (${secDone}/${secTotal})\n\n`;

      if (sec.problems && sec.problems.length > 0) {
        sec.problems.forEach((prob) => {
          const check = prob.completed ? "[x]" : "[ ]";
          const link = prob.url ? `([Link](${prob.url}))` : "";
          md += `- ${check} **${prob.title}** \`[${prob.difficulty || "Medium"}]\` ${link}\n`;
        });
      } else {
        md += `*No problems added to this section yet.*\n`;
      }
      md += "\n";
    });
  }

  md += `---
*Exported from AlgoCraft Sheets Studio — Track your progress anywhere!*
`;

  downloadFile(safeFilename, md);
}

/**
 * 3. Export Candidate Profile & Prep Portfolio
 */
export function exportProfilePortfolioMarkdown(profileData) {
  const safeFilename = `algocraft_candidate_portfolio.md`;
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric"
  });

  const md = `# 🎓 Candidate DSA Preparation Portfolio
**Generated on:** ${dateStr}
**Platform:** AlgoCraft (100% Free AI DSA Mentor)

---

## 📊 Preparation Metrics
- **Current Problem Solving Streak:** 🔥 ${profileData.streak || 1} Days
- **Total Problems Deconstructed:** ${profileData.totalSolved || 0}
- **Mastery Distribution:**
  - Easy: ${profileData.difficultyBreakdown?.Easy || 0}
  - Medium: ${profileData.difficultyBreakdown?.Medium || 0}
  - Hard: ${profileData.difficultyBreakdown?.Hard || 0}

---

## 🏆 Mastered Solutions & Notes
${
  profileData.savedSolutions && profileData.savedSolutions.length > 0
    ? profileData.savedSolutions
        .map(
          (s, idx) =>
            `${idx + 1}. **${s.title}** \`[${s.difficulty || "Medium"}]\` - *${s.category || "DSA"}*`
        )
        .join("\n")
    : "- Solutions deconstructed in AlgoCraft Studio will appear here."
}

---
*Verified via AlgoCraft Interview Studio*
`;

  downloadFile(safeFilename, md);
}

/**
 * 4. Trigger Clean Print Layout
 */
export function triggerPrintableLayout() {
  window.print();
}
